### ISSUE TITLE
Improve readers message retrival querying

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#1061]
When getting messages from reader it would be nice to have possibility to have more flexible query of the results. For example `give me all messages that name contains "appartment"`
we can have messages where names are `appartment1,appartment2,appartment3` 
and it would be good to retrieve all these messages in a single http request like this
`curl -S -H "Content-Type: application/json" -H "Authorization:8bf59204-aa6a-4efd-a646-e3ca0b049c3e" -X GET https://clover.mainflux.io/pgreader/channels/cb4b3cbf-ee82-44d9-9723-9dda7b86469d/messages\?offset\=0\&publisher\=3ad0f341-42d3-49e8-8dbb-6b08dda4de2c\&limit\=100\&name\=appartment`
so name would be checked against data in databse with something similare to `select * from messages where name like 'appartment%'`

**Comment by manuio** [comment]
It would be also very useful to be able to fetch messages for a certain period in order to implement date range pickers from applications.

**Comment by manuio** [comment]
@mteodor btw, isn't name filter already available here: https://github.com/mainflux/mainflux/blob/master/readers/influxdb/messages.go#L130 ?

**Comment by manuio** [comment]
@mteodor the problem is that these filters are generated in these functions:
 https://github.com/mainflux/mainflux/blob/master/readers/mongodb/messages.go#L113
 https://github.com/mainflux/mainflux/blob/master/readers/cassandra/messages.go#L99
 https://github.com/mainflux/mainflux/blob/master/readers/postgres/messages.go#L83
 
 We are generating a `map[string]string` using this fields: https://github.com/mainflux/mainflux/blob/master/readers/api/transport.go#L33 and it's hard to understand how this is propagated in the code. Also,  if we support`"value", "v", "vs", "vb", "vd"` this should be documented. Maybe it would be better to be more explicit  and use
 a structure. Something like  we did for things service: 
 ```
     pageMetadata: readers.PageMetadata{
	    Offset:   o,
	    Limit:    l,
	    Publisher: p,
	    Value: v,
	    Name: n,
	    From: f,
	    To: t,
    }
```
