### ISSUE TITLE
Remove Vault API client from certs service

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#1225]
2. Describe the feature you are requesting, as well as the possible use case(s) for it.

Vault API client brings lots of dependencies and doesnt bring much benefit in comparison to using Vault HTTP API

**Comment by mteodor** [comment]
with removing vault api client this should also be tackled https://github.com/mainflux/mainflux/pull/1221#discussion_r460694927

**Comment by drasko** [comment]
@mteodor can this one be closed?

**Comment by drasko** [comment]
@arvindh123 please take a look at this one and close it if it is not needed anymore, or will not be needed in the near future (explain with the comment).

**Comment by arvindh123** [comment]
### In Brief: 
Instead of using `client.RawRequest` of VAULT SDK , we should use `client.Logical().Write(...)`    
`client.Logical().Write(...)`  was used by the VAULT CLI   

 `client.RawRequest`  should not used directly as mentioned in document  [https://pkg.go.dev/github.com/hashicorp/vault/api@v1.8.1#Client.RawRequest](https://pkg.go.dev/github.com/hashicorp/vault/api@v1.8.1#Client.RawRequest)


### In Detailed : 
In `certs` service, VAULT GO SDK is used for issuing and revoking certificates from VAULT. We are using function `client.RawRequest` of SDK to sending request to VAULT. The code was present here https://github.com/mainflux/mainflux/blob/master/certs/pki/vault.go#L121   

`RawRequest` performs the raw request given. This request may be against a Vault server not configured with this client. This is an advanced operation that generally won't need to be called externally.
Deprecated: This method should not be used directly. Use higher level methods instead.
Reference : https://pkg.go.dev/github.com/hashicorp/vault/api@v1.8.1#Client.RawRequest

As given in VAULT SDK docs , Instead of client.RawRequest we need to use higher level methods,
To access the VAULT API we can use the following function https://pkg.go.dev/github.com/hashicorp/vault/api#Client.Logical
To write and read request we can use this function
 example  for write: `client.Logical().Write(...)`
 example  for read `client.Logical().Read(...)`

 ### Fix PR
This will be solved in PR https://github.com/mainflux/mainflux/pull/1693
