### ISSUE TITLE
run make rundev :> ./run.sh: line 24: gnatsd: command not found

### ISSUE THREAD

**Issue by magixmin** [absmach/magistrala#1321]
**BUG REPORT**
if found ./run.sh: line 24: gnatsd: command not found , 

https://github.com/nats-io/nats-server.git

i search in websit . the gnatsd has change to nats-server ?
need you to change cmd to nats-server

**Comment by magixmin** [comment]
i build in centos 7.5 can not found gnatsd .please help me

**Comment by manuio** [comment]
Looks like NATS recently renamed `gnatsd` -> `nats-server`. You can try following this: https://docs.nats.io/nats-server/installation and if you succeed fixing the issue with the script we would appreciate a PR! 

Also, can you edit the title of the issue with something more detailed instead of an error log, please?

**Comment by magixmin** [comment]
ok  i will reinstall it .

**Comment by magixmin** [comment]
go rundev  need install more things . i use it with docker .can be right .

**Comment by manuio** [comment]
To run `make rundev` you first need to install all dependencies natively. You will also need to build Mainflux services locally. 
If you are trying do deploy mainflux with docker use the command `make run` (docker-compose -f docker/docker-compose up). That way you will pull docker images of any dependency or mainflux service from Dockerhub.

**Comment by magixmin** [comment]
OK， done docker is  better，Save a lot of trouble
