### ISSUE TITLE
flag provided but not defined: -mod

### ISSUE THREAD

**Issue by wudehua2016** [absmach/magistrala#1364]
I follows the guide and just enter the command:
 make cli
but an error comes out:
CGO_ENABLED=0 GOOS= GOARCH=amd64 GOARM= go build -mod=vendor -ldflags "-s -w" -o build/mainflux-cli cmd/cli/main.go
flag provided but not defined: -mod
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
Makefile:67: recipe for target 'cli' failed
make: *** [cli] Error 2
so what is the problem?

**Comment by nmarcetic** [comment]
@wudehua2016 Just tested, works like a charm. If you expect to get community help, you must provide information, otherwise, nobody can help and guess the problem, without superpowers at least. 
Also, there is an issue template, which you don't use. Opening issue is freestyle format (not following the template) is not really helpful.

Please provide the following info: 

* What operating system and processor architecture are you using (go env output)? 
* What version of Go are you using (go version output)?

**Comment by manuio** [comment]
@wudehua2016 It's also working for me. I'm using `go1.14.2 `. Closing this one for now.
