### ISSUE TITLE
failed to parse chinese for mqtt

### ISSUE THREAD

**Issue by yhyf** [absmach/magistrala#1428]
when I use mqtt.fx publish senML messages which contains chinese char to mqtt server ,I received invalid char fault

**Comment by dborovcanin** [comment]
Please fill out the [issue template](https://github.com/mainflux/mainflux/issues/new) properly (this is a bug report type). Is this error caused by an invalid character in the payload or in the MQTT topic? In which env is it happening? Which version of the MQTT adapter are you using? Can you share the error log?

**Comment by dborovcanin** [comment]
@yhyf  Any plans on updating this issue? We do not have sufficient info to start working on it.

**Comment by drasko** [comment]
Closed due to inactivity.
