### ISSUE TITLE
Policies for Things sharing

### ISSUE THREAD

**Issue by buraksekili** [absmach/magistrala#1454]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Instead of an ownership-based approach, `Things` should be shared among entities via Policies. So that, each entity that has the policy to access a `Thing` should be able to access the `Thing`. Or, if the entity has no policy to access a Thing, the entity should not access a Thing.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
must-have

Some tasks for further steps:
- [ ] After deleting a `thing`, delete the policy related to that particular `thing`. It requires adding a new gRPC endpoint.

**Comment by drasko** [comment]
@nmarcetic please enumerate here options for listing shared Things, so that we start discussing the best option for this complex requirement.

**Comment by nmarcetic** [comment]
The issue that comes out is related to all listing requests, where things are returned in a batch like search/list endpoints. 
How policies will affect this ?
Additional policy action can be added like `can_filter` `can_search` , but even simple `can_read` can work. The actual problem is how to match policies (one or many) vs slices of things returned from the database as a result of the request. 
Iterating over the result and looking for the matching policy? What is the requesting user have a policy for 10 things, but not for the rest in results returned from the database? Should we return only matched one or? 

Can the group solve this? Probably, but not fully 
For example put all things that you want to t share with the user in a group like `sharedGroup`, when the user makes a search request we can match if those things in the result belong to a shared group.
This is good, but what if things don't belong to this shared group but the user has a dedicated policy for this thing? So we need to check this too. 

Example Pseudocode 
// search result = requested search result fetched slice of things from DB as we are doing now. 
* Iterate over the search result 
  * Check if the user has a policy dedicated policy for a thing
     * Check if this thing belongs to any group that user have access to (read policy) 
        * true append thing to search response
        * false, skip this thing and exclude it from search response

**Comment by dborovcanin** [comment]
Another option for listing is to use it as @nmarcetic mentioned, with `can_filter`, `can_search`, or even simple `can_read` but return only partial information about the entity. For example, the list response for Things includes name and ID but does not include metadata, key, connected channels, groups... This way, we limit user access to entities, but we also allow performing listing and accessing entities in a way.
