### ISSUE TITLE
500 Internal server error while Publishing Values on a Channel

### ISSUE THREAD

**Issue by chandrasekar-vlsi** [absmach/magistrala#149]
**Getting Client token**
curl -s -S -i --noproxy localhost -X GET -H "Content-Type: application/senml+json" -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MTcyNTI1NzIsImlhdCI6MTUxNzIxNjU3MiwiaXNzIjoibWFpbmZsdXgiLCJzdWIiOiJxd2VydHlAZW1haWwuY29tIn0.EA1pl0hEC-Lh23-2hW0jmtsdH1sK5ftliXv_ImVMGuE" localhost:8180/clients/4ebcd629-04d3-11e8-a7c1-0242ac110005
_**Response**_
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Mon, 29 Jan 2018 09:09:48 GMT
Content-Length: 273
{"id":"4ebcd629-04d3-11e8-a7c1-0242ac110005","type":"device","name":"weio","key":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MTcyMTY2MjQsImlzcyI6Im1haW5mbHV4Iiwic3ViIjoiNGViY2Q2MjktMDRkMy0xMWU4LWE3YzEtMDI0MmFjMTEwMDA1In0.f-tk4tGECoEEz7dUBlFpoKEYiuub9udkpy_gCChFQ1g"}

**Publishing Values**
curl -s -S -i -X POST -H "Content-Type: application/senml+json" -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MTcyMTY2MjQsImlzcyI6Im1haW5mbHV4Iiwic3ViIjoiNGViY2Q2MjktMDRkMy0xMWU4LWE3YzEtMDI0MmFjMTEwMDA1In0.f-tk4tGECoEEz7dUBlFpoKEYiuub9udkpy_gCChFQ1g" localhost:7070/channels/80843337-04d3-11e8-a7c2-0242ac110005/messages -d '[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3}]'
_**Response**_
HTTP/1.1 500 Internal Server Error
Date: Mon, 29 Jan 2018 09:12:16 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

**Comment by mijicd** [comment]
Error status is already fixed in #146, however, it might indicate usage of "wrong" token on the channel. I would suggest the following course of actions:
- stop & remove the existing mainflux images (it is enough if you do this with manager and http adapter)
- pull & run the new images
- create user, client, channel
- connect client to the channel
- publish message to the channel using the key of the connected client

**Comment by drasko** [comment]
@chandrasekar-vlsi can you please do GET on the `/channels/80843337-04d3-11e8-a7c2-0242ac110005` and confirm that device is "connected" to this channel?

I.e. you need this step: http://mainflux.readthedocs.io/en/latest/getting-started/#grouping-clients-by-connecting-them-on-channels in order to publish on a certain channel.

**Comment by chandrasekar-vlsi** [comment]
Thanks mijicd and drasko, i have pulled and started new images and working fine...
where can i get complete list of API documentation for mainflux?

**Comment by drasko** [comment]
@chandrasekar-vlsi official documentation can be found here: http://mainflux.readthedocs.io/en/latest/. For the API reference take a look at Swagger files in services' repos.

Closing this one.
