### ISSUE TITLE
Improve persistence layer

### ISSUE THREAD

**Issue by mijicd** [absmach/magistrala#159]
The following issues "common" problems are identified from #131, #133 and #150:

- management of clients, channels and users require strong consistency
- JVM is unacceptable dependency in constrained environments
- messages need not to be permanently stored
- deployment requires "pre-start" actions (e.g. creation of keyspaces, startup time)

Re-evaluation of architectural design decision, lead us to the following decisions:

- Apache Cassandra will be dropped from the core platform
- [CockroachDB](https://github.com/cockroachdb/cockroach) or PostgreSQL will be used as primary storage 
- if necessary, constrained deployments will replace it with [BoltDB](https://github.com/coreos/bbolt)
- messages will not be persisted
- `writer` service will emit stream of normalized messages
- streamed messages can later be used by analytics, rules engine or any other consumer

**Comment by drasko** [comment]
## CockroachDB
- https://www.cockroachlabs.com/blog/run-cockroachdb-on-a-raspberry-pi/
- https://github.com/cockroachdb/docs/issues/1132
- https://stackoverflow.com/questions/34978809/can-cockroachdb-run-on-raspberry-pi

Cocnlusions:
- Targets 64-bit processors, without any tests/support for 32-bit
- Tweeks are needed to put it on RPi
- Recompilation is needed
- There are no binaries or .deb packages for RPi
- No Docker images prepared

## PostgreSQL
- https://www.raspberrypi.org/forums/viewtopic.php?t=5964
- https://bpwalters.com/blog/setting-up-postgresql-on-raspberry-pi/
- https://hub.docker.com/r/rotschopf/rpi-postgres/
- https://www.enterprisedb.com/docs/en/9.3/pginstguide/PostgreSQL_Installation_Guide-04.htm

Conclusion:
- Easy to install, even on RPi
- Stable support for 32-bit
- Provided Docker images for RPi
- Lower HW requirements

Overall observation: having in mind that we do not need scalability on the Manager persistence component, because a single PostgreSQL will be capable to handle millions of entities (users, device and channles) and the fact that PostgreSQL has easier instalation on gateways, I am leaning to Postgres. Not to mention product maturity and tooling.

@mijicd @janko-isidorovic one thing to consider: currently auth is embedded in Manager and every req is checked upon Manager storage. How will this impact geographically spread deployments? Would CockroachDB multi-datacenter capability help reduce latencies here (even if we do not need a need for extra storage, maybe pure facst that we can sync geographically remote locations would help). I know that Postgres can be also spread, especially for reads, but never the less.

Let me try to install both bases on RPi in the following days for further study.

**Comment by mijicd** [comment]
@drasko As you know, I was in favor of PostgreSQL from the beginning: it's capabilities are more than enough for Mainflux. Therefore, I wouldn't spend much time any more, solving problems that we don't even have. From the perspective of implementation, there's no difference anyhow, let's go with PostgreSQL and migrate to CockroachDB only if we need.

**Comment by drasko** [comment]
@mijicd fully agreed. Let's proceed with PostgreSQL, we'll see later if there is a need for switch. In any case, since both DB use Postgres Go driver, it should be trivial in-place replacement.
