### ISSUE TITLE
Split manager service

### ISSUE THREAD

**Issue by mijicd** [absmach/magistrala#164]
In current setup manager service takes care of all authentication and authorization concerns. With latest architectural changes introduced in #159, it makes sense to extract this functionality into separate service.

**Comment by chombium** [comment]
continuing the discussion here as requested by @mijicd 
------ copy-paste from #169 ----------
@chombium:
    I think at some point (maybe after 1.0) we should enable connectivity to external authorization and device management systems. We could add adapters for different authentication and device management system. This is important for bigger organizations with central user and device management systems. If some organization has already setup their IT infrastructure and they are managing everything centrally, we'll have to have good APIs with which they can do the integration.

@drasko:
I am OK with this, but what will be then the use of Mainflux system - if device management already exists? Pure messaging?
------ end copy-paste----------
@drasko: sorry for the late reply... Of course I don't want to see Mainflux used only for messaging. I'm thinking more of single source of identity management for the devices. If some organization already has some sort of device management system in which they manage the data of the devices (UIDs and other parameters) I think in cases where the organization already has some device management, we should not generated our own device IDs when provisioning the devices in Mainflux, but build an API with which we can get the needed device data from an external system. This way the users will not have to build some sort of device ID mapping between Mainflux and the other external systems in order to be able to track the devices and their data.
I think from a user point of view it would be much better if we have an API with which we can get some device data from an external system, than to force the users to spend time in syncing the data between Mainflux and the other system in order to track the devices. The communication rules are of course Mainflux specific and will be stored on our side.

**Comment by mijicd** [comment]
The implementation should split manager service into two separate services: `users` and `clients`.

**Users** service will expose a public HTTP API (similar to the current one) for creating user accounts, and generating access tokens. Besides that, it will expose an internal gRPC API that will be used by **clients** service (for now). In the future, it can be used as point of integration for any additional auth scheme. 

**Clients** service will expose a public HTTP API (similar to the current one) for managing devices,  apps and channels. Besides that, it will expose an internal gRPC API that will be used by the channel adapters to check access permissions. In order to verify the provided credentials during resource creation, the service will rely on gRPC API provided by **users** service.
