### ISSUE TITLE
Provide optional message writing facilities

### ISSUE THREAD

**Issue by mijicd** [absmach/magistrala#208]
Due to the changes introduced in #159, `writer` service has been removed from Mainflux. While the decision is to keep the core platform agnostic to the way messages are persisted, and produce the stream of normalized messages instead, some customers might need to persist these as well.

That being said, new `writer` service should provide various DB repository implementations, that are to be instantiated at runtime based on the service configuration. First release will contain only the PostgreSQL repository, while separate tickets will be created for any additional implementations (e.g. MongoDB, InfluxDB, Cassandra).

This new service will consume the stream of messages generated by `normalizer` and store them. The only interface it needs to support should look like:

```golang
type MessageRepository interface {
    Save(Message) error
}
```

**Comment by chombium** [comment]
I was also thinking about this and wanted to open a ticket about this as well, but I guess you were faster :)

I think that we should only define and provide a DB (persistance) interface which will describe and the boilerplate to tap on the messages in NATS.

I think that some users would not want to store all the messages. They will simple read the messages add apply some analytical functions and store the aggregated values to the database. It would be nice if we design the whole message writing so that some rules and message processing can be applied before writing the values to the database. Simple example: The room temperature is measured by a sensor which returns the temperature in Celsius, but the the user is based in the US and he want's to have the values in Fahrenheit as unit of measure. In such cases it would be nice to have a way to filter and process the messages before writing them in the database. The message stream from the normalizer will go through a filtering (rules) engine and pre-processor before writing the messages to the database.

If we persist all the messages as they are received and processed by the normalizer, in order to avoid DB read pooling from the business apps built on top of  Mainflux, it would be nice if we have some kind of notification fired when a new message has been written to the DB so that some additional data processing can be triggered(started) in order to start some data processing.

I know that this ticket is about saving the normalized messages directly to the database, but I just wanted to write down the ideas which I have. I'm aware of the rules engine poc in the labs repo, but I don't know what's it status.

Shouldn't we also open a ticket for service which will read messages and publish them in NATS?
Simple example: A massage from the normalizer is written in the DB, some external app reads it directly from the DB processes the data, writes some new data record which should be published to NATS so that it can be consumed by other services.

What do you think about this scenarios?

**Comment by mijicd** [comment]
@chombium these writers are intended to serve as utilities for customers that want to store normalized messages for any reason. They are not intended to be part of "standard" deployments, since I would prefer to apply post processing on top of message stream generated by the normalizer. Rules engine that will soon start to be integrated in the platform will take care of the "load" placed on the system. 

Regarding the reader path, we have discussed this a lot and decided not to provide such service. We think that reading raw values through our APIs might not be as valuable as providing aggregated/post-processed values and predictions. Thus being said, some of those post-processing steps you mentioned above will be provided together with some additional steps as part of our analytics solution (working project name), which we do not intend to open source.

**Comment by chombium** [comment]
@mijicd Thanks for the answer.

Not providing reader seems reasonable to me, but still, I think it would be interesting if we at list define an interface, so that if many vendors build analytics solutions on top of Mainflux, interoperability between the solutions and the components will be assured. This way we'll have drop in components which will seamlessly integrate and work with one with another. 
Who knows maybe some day we'll have a marketplace for various components and solutions which will work on top of Mainflux ;)

**Comment by drasko** [comment]
@chombium to which interface do you refer?

Mainflux is doing message brokering, and normalized SenML mesages are pumped out of NATS in the following format: https://github.com/mainflux/mainflux/blob/master/message.proto#L13-L28

It is basically SenML format plus some additional Mainflux-related fields (notably `Channel`, `Publisher` and `Protocol` - https://github.com/mainflux/mainflux/blob/master/message.proto#L15-L17), and should be easy to parse by any analytics engine on the top.

**Comment by chombium** [comment]
@drasko uh I guess I missed that out, sorry. I was thinking on the reader interface definition, simply read a database record and publish it to NATS. 
On the second thought, I completely agree with you, all we need is an example app in which we can show how can the users read, write and process the messages.

**Comment by mijicd** [comment]
Split into #235, #236 and #237.

**Comment by chombium** [comment]
@mijicd I was thinking  of a common payload agnostic nats client which will simply tap on the "normalized" subject and give the read message to the Save method. Every field mapping will be done in the Save method according to the user's needs.
It's good that we agree on that one ;)
