### ISSUE TITLE
Evaluate certificates as client access keys

### ISSUE THREAD

**Issue by mijicd** [absmach/magistrala#271]
I would like to start the discussion on replacing plain-string tokens with certificates (e.g. X.509). What are your experiences, are there any drawbacks, recommendations etc.?

**Comment by windbender** [comment]
X.509 could work. Additionally an HMAC type system could work as well.  

Consider anything which would allow hardware utilizing a crypto authentication part such as http://www.microchip.com/design-centers/security-ics/cryptoauthentication/cloud-authentication/google-iot-core-atecc608a
to properly authentication against a main flux broker.

This is not idle speculation, both Amazon and Google are utilizing these systems for authentication in hardware devices.  Since IOT hardware is often location in "public" locations with little to no security, it's pretty straight forward to get access to "root" level on these systems with either Serial or JTAG.  Hence an X.509 key (or any PSK) stored on disk is subject to someone lifting it and utilizing it for nefarious purposes somewhere else.
