### ISSUE TITLE
Docker build fails due to grpc vendor files

### ISSUE THREAD

**Issue by fischermario** [absmach/magistrala#340]
I am working on building Mainflux on the RPi. The 'make dockers' command fails due to grpc vendor files:

https://gist.github.com/fischermario/280b0368cc0a067ebdb817122c1a2682

My workaround is to do the following after git clone and changing to Mainflux directory:

```
pi@raspberrypi:~/mainflux $ rm -rf vendor/google.golang.org/grpc/
pi@raspberrypi:~/mainflux $ git clone https://github.com/grpc/grpc-go vendor/google.golang.org/grpc
```

This solves the problem. Can you confirm this?

Why is there a local copy of the grpc repo in the first place when the 'go get' command tries to aquire a more recent copy?

**Comment by dborovcanin** [comment]
Hi, we can confirm this problem. It's up to the wrong version of the `grpc` we've vendored. Please, take a look at this issue: https://github.com/grpc/grpc-go/issues/2121. The reason we have a local copy of the `grpc` is that we keep `vendor` directory in our repo in order to provide reproducible builds. More on vendoring you can find [here](https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory).
You can solve a problem like you did, but also, running `dep ensure` before `make dockers` should work just as fine. Please let us know if this answer helped you and close this pull request if so.

**Comment by fischermario** [comment]
Thank you for the insight! I think you can close this issue.
