### ISSUE TITLE
Enrich things with additional metadata / traits 

### ISSUE THREAD

**Issue by nwest1** [absmach/magistrala#342]
**FEATURE REQUEST**

Hi - looking to contribute here but would like to discuss the idea first.

I'm proposing to add additional technical detail to a `thing` including:
- ~~device metadata (serial number, hardware version, etc.)~~
- technical interaction details - value ranges? A schema (if any?) 

## ~~Metadata:~~
~~Generic k/v pairs?~~
~~Or possibly hard-coded column names in addition to the ability to add K/Vs? examples:~~
- ~~manufacturer~~
- ~~serial number~~
- ~~vendor~~
- ~~model~~
- ~~hardware version~~
- ~~datetime stamps for created/last communication~~

## Interaction details:
All these would be user-defined. 
`things` have `types`
`types` have `traits`

Types examples:
- temperature sensor
- button
- refrigerator

Traits examples:
- temperature sensor
- button state
- button action
- firmware push

Each trait would have a schema (json, etc.) associated with it and an interaction method - basically describing the api. 

_Edit: Striking metadata from this convo_

**Comment by chombium** [comment]
Hi @nwest1,

We have one string field in the thing model which was unluckily named [Payload](https://github.com/mainflux/mainflux/blob/master/things/things.go#L13). It is intended to be used for some free structured metadata. You could store some data structure in form of serialized JSON for example. As we can not cover every single needed field, we kept it that way, so that everyone has a possibility to add some extra data to the thing instances.

You can try using it as a start.

Could you be kind to give us some use cases for the proposed changes, so that we can kick of the discussion and make some thoughts how can we solve this better?

@drasko, @nmarcetic, @anovakovic01, @dusanb94 what are your thoughts on this?

**Comment by drasko** [comment]
@chombium initially `Payload` was called `Metadata`, and I would like that we bring back this old naming. `Metadata` is JSON string map, generic enought that you can put anything that you want.

We can not guess if somebody needs `manufacturer` and somebody else `serial_number`- just put everything you need in `Metadata` and parse it yourself in the custom `writer`.

**Comment by drasko** [comment]
@nwest1 idea looks interesting, but we'll like to keep things as simple and as lean as possible.

I think that all that is needed can be resolved with custom `writer` code, but maybe we can think of plugins or ways to add custom code to `normalizer/writer`-like services to parse custom `Metadata` JSON schemes and shoot the messages to NATS.

**Comment by drasko** [comment]
@nmarcetic @evarga @janko-isidorovic @gesaleh @anovakovic01 @dusanb94 @darkodraskovic I would like to hear your opinions on this and how can we approach these improvements that @nwest1 proposed.

If further explanations later are needed maybe @nwest1 can make a spec in the form of shared Google doc where we can comment these architectural improvements. I believe that these propositions actually come from real-world use-case and needs, that's why they are interesting.

@chombium what's your opinion, if we are to add some user-definable plugins or configs, what would be the best approach while keeping the arch lean?

**Comment by dborovcanin** [comment]
> @chombium 
Could you be kind to give us some use cases for the proposed changes, so that we can kick off the discussion and make some thoughts how can we solve this better?

I think this is really important. As @drasko said, we're trying to keep things as simple and as generic as possible. If there are some use cases that we don't cover, then yes, architectural changes are not just welcome but needed. Also, I think that renaming this field back to `Metadata` is a good idea, we can open an issue for that one.

**Comment by anovakovic01** [comment]
@drasko Users would probably like to have powerful search API for this metadata. I would suggest using separate NoSQL database, like `ElasticSearch`, to store this metadata in.

**Comment by nwest1** [comment]
Thanks for the discussion! And please forgive my ignorance as I'm fairly new to the space - I have a lot to learn! 

I think you've totally answered my metadata question, and am in total agreement.

The second part (interaction details) is an attempt to document the specific input/outputs of a device. For example, if I want to be able to deploy several of these http://thingysticks.com/Environment/V2/ in a datacenter. This particular device can output Light, Humidity, Temperature, Pressure, and RelativePressure. I would like to be able to document those capabilities in a way to validate messages, inform code or at the very least allow users and developers to understand what they can expect from a particular device.

I'm happy to get more detailed on a collaborative doc if we need. I didn't want to get too far down the wrong road before getting some feedback about this. Thanks again!

This is a bit beyond this specific topic but would there be value in having some sort of community-maintained set of definitions for all the available products out there?

**Comment by nwest1** [comment]
It looks like there already is something community-managed & this also seems to be the closest to the kind of data I was expecting to be stored to define a `trait` (`capability` might be a better word) (Light/Humidity/etc.) or suite of capabilities for a `thing`

https://oneiota.org/revisions/2991

**Comment by drasko** [comment]
@nwest1 the discussion you started here makes perfect sense, and thank you for this. An issue for renaming `Payload` back to `Metadata` was opened by @chombium and assigned to @blokovi : https://github.com/mainflux/mainflux/issues/343

The only problem in keeping this info in `Metadata` field is that complex querying on any of these fields is not possible, as they are all stacked into one 2-dimensional array (i.e. JSON string map) which is put in SQL DB (in this case PostgreSQL). This is why @anovakovic01 proposed additional NoSQL DB to hold this `Metadata` field, and facilitate complex queries. This sounds as an interesting proposition to me, but let's develop a use-case a bit further, to see what is best approach. As TANSTAFL, additional DB will augment complexity, but more importantly it will make Mainflux system more difficult to deploy on modest gateways.

Regarding ThingySticks modules, I think you will not have any problem sending data from them via MQTT and current API that Mainflux exports. You can follow the _Getting Started_ guide to provision your system (create users, things, apps and channels and connect them together): https://mainflux.readthedocs.io/en/latest/getting-started/ and then use Mainflux MQTT API: https://mainflux.readthedocs.io/en/latest/getting-started/#mqtt to send messages about measurements of sensors to some Mainflux channels to which your apps are subscribed.

For publishing MQTT messages from Particle Proton/Electron firmware to the cloud, you can take a look at this tutorial: https://www.instructables.com/id/Spark-Core-Photon-and-CloudMQTT/

I think you can do several configurations here:
- Have one `channel` per thing
- Have one `channel` per what you refer to as `trait`
- Some combination of both

Your application(s) that is connected to the Mainflux `channel`(s) that you created will know, based on you system provisioning (which `channel` is used for what, etc...) how to present the incoming messages.

Note also the semantics of Mainflux - we use [SenML](https://tools.ietf.org/html/draft-ietf-core-senml-16) to represent the messages (measurements from the sensors). For example, one SenML message of this type: `{"n":"my_temperature_sensor_123","u":"Cel","v":23.1}` clearly shows the name of the measurement, the unit and the value.

Based on all of this, Mainflux is just a low-level simple message passing mechanism with security (access control) and very few entities. Other stuff - like describing `traits/capabilities` and min/max values should be offloaded to a specific application/microservice that lies on the top of the Mainflux, IMHO (actually defining min/mac values, setting up the alarms and sending the alerts should be part of Rules Engine microservice that would be very useful as a generic microservice connected to NATS and living between NATS and user app as a stream processing block. We have planned this microservice, but is was never implemented due to the lack of time).

**Comment by drasko** [comment]
@anovakovic01 if strong consistency is not needed for users/things/channels/apps entities, maybe we can consider [CouchDB](http://couchdb.apache.org/) - based on EdgeX Foudry research it is small enough to be run on the gateway and it has appropriate licensing (Mongo is AGPL) and can run on 32-bit ARM machine (yey Erlang :)).

But what I particularity like with CouchDB is its syncing mechanism, i.e. replication protocol: http://docs.couchdb.org/en/master/replication/protocol.html - and this cna be extremely important for IoT gatewyas with intermittent connections, as upon the reconnection to the cloud, gateway can seemlesly update its local storage. Take this for example: https://pouchdb.com/ and think of IoT gateway as a mobile phone (same problem of temporary disconnections).

**Comment by chombium** [comment]
@nwest1 as @drasko already explained in detail why do we keep the things as simple as possible, for the time being with the current Mainflux implementation you could create a custom [writer](https://github.com/mainflux/mainflux/blob/master/writers/writer.go) (check the writer folder for examples) which will pick up the messages do the validation and process them further (write them to db, send them somewhere else etc.)

@drasko I'm sorry to be a party breaker ( I know that you are really fond of Erlang) :), but instead of complicating the things by adding some new NoSQL DB, we can use one of the built-in PostgresSQL features, that is [JSONB](https://www.postgresql.org/docs/current/static/functions-json.html). If we change the Payload(Metadata) field in the Thing model to be stored as PostgreSQL JSONB, we could query the JSON fields with built in PostgreSQL functions, here some examples:
http://schinckel.net/2014/05/25/querying-json-in-postgres/
https://www.compose.com/articles/could-postgresql-9-5-be-your-next-json-database/
https://hackernoon.com/how-to-query-jsonb-beginner-sheet-cheat-4da3aa5082a3
http://redgreenrepeat.com/2017/03/17/postgres-key-value-reference-card/

Here are some examples (and libraries) how to handle JSONB in Go:
http://coussej.github.io/2016/02/16/Handling-JSONB-in-Go-Structs/
https://gist.github.com/iampeter/fe98029d193e0bba421a3c18bbd45e4c
https://medium.com/@thedevsaddam/query-json-data-using-golang-76b6ab974dd6
https://upper.io/db.v3/postgresql

I only listed the links here, I'll play a bit with JSONB in the next few days.
Switching to JSONB would be the easiest thing to do without to many changes.

It might be nice if we can define the different properties of a thing. For example I have a smart sensor which can measure temperature in Celsius and relative humidity. 
To build such work flow in which the users create a thing and add few properties, we would need to introduce at least two new entities Property and UnitOfMeasure.
Their structure would be:
* Property: Name, Description and optionally UnitOfMeasure
* UnitOfMeaure: Name, Description, Symbol

This way there will be a clear what a thing (sensor) can do and with which data it can operate, but I find it a bit opinionated and will impose a certain structure of the things, which we don't want to do.

We definitely need a concept for extending the functionality of the Mainflux's components, but I doubt that we need some special or complex plugin mechanism.
What I think is that we need are couple/series of developer guides (youtube videos) in which build a complete system which receives the messages adds some extra processing with custom NATS clients (similar to what we have with the writers) and makes some use of the data.

I think that the biggest problem is that all the people checking Mainflux think that they should add some custom processing at the beginning in the ingestion phase, be it in the adapters or the normalizer or at the very end after the messages are written in the database with a writer. 
Mainflux uses NATS, and I strongly believe that we should promote using NATS clients to extend the capabilities and the message processing pipeline. This way the people can use what comes with Mainflux out of the box and add extra processing/behavior they need. All the messages (raw and normalized) are published on NATS subjects, so the developers can tap on a specific subject, get the message, add some extra processing and republish it on a different subject. This way they can chain as much NATS clients as they need to get the behavior that they need.

My point of view on the Rules Engine example:
1. A message is received via HTTP, normalized and published back to a NATS subject
2. a metadata service adds some extra data to the original message and publishes it to NATS ona different subject
3. The Rule engine reads the message, checks the value of the measurement and detects that it's an alarm state. It generates an alert and publishes an alert message on NATS subject and saves the alert state in a DB
4. A "notification engine" picks up the alert message and sends e-mail and SMS to inform the operators about the irregular state.

It's quite easy to write NATS clients and I think we should point our users to the right place where they can attach their custom business logic.

I hope I made myself clear ;)

Best Regards,
Jovan

**Comment by nwest1** [comment]
@drasko Thanks for helping me understand where the walls are and why they're there. I really appreciate it. Also, I wasn't expecting the metadata to be a larger conversation vs. what I was thinking about with device-specific capability def'n.

@chombium I'm on board with the writer approach for now - or that might move into whatever we might build on top of mainflux. 

> It might be nice if we can define the different properties of a thing. For example I have a smart sensor which can measure temperature in Celsius and relative humidity.
To build such work flow in which the users create a thing and add few properties, we would need to introduce at least two new entities Property and UnitOfMeasure.
>
>Their structure would be:
> - Property: Name, Description and optionally UnitOfMeasure
> - UnitOfMeaure: Name, Description, Symbol
>
> This way there will be a clear what a thing (sensor) can do and with which data it can operate, but I find it a bit opinionated and will impose a certain structure of the things, which we don't want to do.

I think this is what I was trying to get at - having the ability to define specific properties of a thing would be important for discoverability. I'm not sure how to do that in a simple way without being opinionated about it. Without having more context with this project, I think it's a natural step to make from finding the `things` database to expecting to want to add more details about a `thing` right there. 

If the suggestion is to store these properties at another layer that makes sense, but would it be useful to define a "focused" SenML schema? Defining names/units/etc.?

**Comment by drasko** [comment]
@chombium thanks for the JSONB - if we can have rich queries on JSON `Metadata` with Postgre then this is great for me. I like Erlang, but I am really not a fan of adding a new service just to handle Matedata.

However - I do not really like the idea of adding `Property` and `Unit` fields on the first look... What do we really get with this? SenML has `"u"` field that holds unit. Also - one device can have many `Properties` - think of complex device like a car that has many sensors and actuators. In some configuration this can be represented as just one `thing` sending various values on various `channels`.

Many of the organizations tried with opinionated approach - from IPSO to OCF and they do not look like they are getting much popularity despite huge work put into standardization. Also - how do you describe the `Property/Unit` for GPS or gyroscope - they have several values at the same time. Then the combinations and potential descriptions will become more and more complex...

I propose that we do this one step at the time and really observing the use-cases and demands that will come from real-world customer projects. Lets start with the following:
- Well defining `Metadata`
- Making `Metadata` searchable (enable complex queries)
- Educate users on how `Metadata` should be used - provide documentation, examples, blogs and other training material

After that we can brainstorm how to allow custom thing and/or message schemas, but if we go down this path I would rather turn towards IPSO or OCF support and stay aligned to OMA/OCF standards.

**Comment by drasko** [comment]
@nwest1 SenML is message format, not a schema of device (`thing`) entity. Messages are published by `things` or `apps` on `channels`, but one `thing` can be sending totally different kind of SenML messages on the different channels or even on the same channel. Mainflux does not limit you as an IoT system architect  - it's up to you to set-up, provision and configure your system - declare`things`, `apps` and `channels`, connect them and flash the correct firmware in your devices. Depending on the firmware in device - it can send different or same SenML messages - it's your choice. You can treat complex device with many sensors as one `thing`, or you can declare one `thing` entity per sensor - again it's up to you.

While message format is opinionated - and we have chosen SenML (because we need to know message schema to parse it if we want to persist it) - `thing` entity is kept very generic with simplest possible model. Question here is how to keep model simple, generic and yet powerful (i.e. enable complex queries on `Metadata` and facilitate its use).

Speaking about SenML for messages - this is also not completely true - you can send literally any `Content-Type` over API, just that `writer` component will not be capable (of course :)) to parse your custom messages. Never the less - they will be brokered between the protocol adapters and output on the NATS on the topic [out.unknown](https://github.com/mainflux/mainflux/blob/master/normalizer/normalizer.go#L18). If you are sending any custom JSON or binary messages your custom DB `writers` or other processing app should just pick them up from NATS on this topic and you're good to go.

**Comment by drasko** [comment]
Closing this one for now. Reopen if needed.
