### ISSUE TITLE
Naming of channels > MQTT extend topic use (for commands on topic)

### ISSUE THREAD

**Issue by RubenN** [absmach/magistrala#429]
**FEATURE REQUEST**

To be able to use channels (topics) for standard MQTT devices, such as Tasmota (Sonoff) it would be nice to have just a little more control on the naming of the channels:

`channels/1/messages/%this part could be freely chosen%`

For example:
`channels/1/messages/cmnd/sonoff/POWER `

In this way devices that need extended topics can still use the Mainflux message system.
Maybe we can make the regular expression that is used to check the channel name a variable, or even better extend the channel type with a regular expression naming schema, with a fallback to the already existing naming?

**Comment by drasko** [comment]
@RubenN Interesting proposition, but I do not see why `channels/1/messages/cmnd/sonoff/POWER` can not be just `channels/1/messages` and `channels/1/messages/cmnd/sonoff/SOMETHING_ELSE` be `channels/2/messages`. Your app can do this mapping. Channels are abstraction over MQTT topics and have to make sense in HTTP, WS and CoAP world also.

What is currently missing are channel groups - to let a device connect and subscribe to a group of channels.

But I can not really see why Mainflux has to provide these custom topics, especially that then authorization and authentication procedures would have to be much more complex.

Is there something I'm missing?

**Comment by RubenN** [comment]
@drasko Maybe groups of channels could work, but in this case that would mean a lot of definitions for every command a device  understands. 
Of course the firmware for the device could be rewritten, but with my suggestion (letting only the first part (channels/1/messages) be the real channel name and the rest (/cmnd/sonoff/SOMETHING_ELSE) just being passed through without altering would make it possible to use all variants like mentioned here: [Espurna](https://github.com/xoseperez/espurna/wiki/MQTT#root-topic) and [Sonoff-Tasmota](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#command-overview)

Authorization and authentication procedures could still be executed on the same (channels/1/messages) part, so no differences there. 

I think there are a lot of standard, well thought out MQTT capable devices/firmwares that could then (and without altering any firmware) also use the safe message transportation of Mainflux.

**Comment by drasko** [comment]
@RubenN I see, and it is interesting indeed.

From what I see [here](https://github.com/xoseperez/espurna/wiki/MQTT#root-topic) and [here](https://github.com/arendst/Sonoff-Tasmota/wiki/MQTT-Features#mqtt-topic-definition), topic are composed out of `root_topic` and `magnitude_topic`.

In order for these kind of devices to work correctly, we need to enable AuthX to be done on `channels/<channel_id>/messages` - which in this case in `root_topic` and then do not check authorization on all subtopics - i.e. providing auth token for `channles/<channel_id>/messages` device/app will be capable to do any CONN and PUB/SUB of type `channels/<channel_id>/messages/#`.

This looks doable to me but we have to analyze security risk because we are augmenting the attack vector.

@anovakovic01 @srados @chombium @manuIO @dusanb94 @nmarcetic I would like to have your opinion on this.

**Comment by RubenN** [comment]
@drasko Exactly right and opening up Mainflux for a lot of already MQTT cable devices seems like a good idea to me  ;-).

**Comment by dborovcanin** [comment]
This URL-Channel mapping makes sense and seems reasonable for all currently supported protocols and can be done on the protocol adapter level. However, I don't think that it fits in current Mainflux Channel abstraction. Mainflux Channels are really just a communication conduit connecting Things, thus enabling them to exchange messages. That is, Channels are protocol-agnostic, so extended topic, or any kind of topic at all, simply doesn't fit here. However, if we change Channels abstraction sometime in the future, we can change it having this on mind and provide some kind of "extended topics".

**Comment by chombium** [comment]
The feature is interesting as it enables sort of plug&play for some devices and will make us think how to support connecting of off-the-shelf devices with minimum configuration.
For the implementation I'm thinking in the same direction as @dusanb94. Adding some mapping similar to URL rewriting in the web servers, could do the trick if we don't want to introduce some breaking changes, but I think that these requested changes are too specific to a certain class of devices and protocols (MQTT) in this case. 

Wouldn't it be better when a separate specialized MQTT adapter is built which will handle this special case? It would listen on the already defined or even a separate NATS subject, pack the MQTT messages and send them out to the devices.

Even if we implement the requested feature, we can not guarantee that all of the devices will be put in the same channel. Let's say that we have one device which measures temperature `my_dev/temperature` and humidity `my_dev/humidity` and for some reason these two topics are configured to different Mainflux channels. What should happen if I want to query all of the measurements and I send only `my_dev` as a topic. The adapter would have to be intelligent enough to check all the channels and the topics that a user has, pack the data together and send it back as a response. That's of course to much.

I'm thinking for some time now, how could we add better flexibility to the data processing flow, but I still haven't opened a ticket to start a discussion. For some use cases, some extra processing steps in between the services which come with Mainflux might be needed. At the moment we have hardcoded NATS subjects on which the services publish and subscribe: the raw messages are received with the protocol adapters and a published on fixed NATS subjects on which the normalizer is subscribed, then the normilzer publishes the messages back to NATS and the writers pick up the normalized messages... I think it would be nice if we add some flexibility and enable "rewiring" the services and adding some extra user based custom services which will act as middleware or something like callback functions in javascript and do some extra processing based on the user's needs. In order to add this,  we only need to take the hardcoded publish and subscribe config outside and let the users adjust the wiring of the services as they need it. We should use the power of the message bus which we have :)

In this particular case this would mean, that after the messages are received with the mqtt protocol adapter they are enriched by a user component to set the channel based on the Mainflux user and MQTT topic and then are sent to the normalizer for further processing. This way we won't expose any Mainflux internals to the outside world and for the people doing the messaging on the other side will do what they are used to (they will not set some unusual root topic because of Mainflux).

What do you think about that approach?

Regarding the authorizations I agree with @drasko. We might also add some check about the MQTT topics to make sure that they don't have some weird things in them (js code for example)

**Comment by drasko** [comment]
@chombium 
> Even if we implement the requested feature, we can not guarantee that all of the devices will be put in the same channel. Let's say that we have one device which measures temperature my_dev/temperature and humidity my_dev/humidity and for some reason these two topics are configured to different Mainflux channels.

This is not completely true, because subject is always composed of `root_topic` and `suffix_topc`. So it would never be `my_dev/temperature` but `channels/<channel_id>/messages/my_dev/temperature` - and then we can track authorization via `root_topic`, which is `channels/<channel_id>/messages`. Of course - `channels/<channel_id>/messages/my_dev/temperature` and `channels/<channel_id>/messages/my_dev/humidity` will be different topics, and channels will have only one purpose - for access control.

I think this will not be hard to do and would not demand a lot of changes. This can also be made optional by config, for the people who need this feature.

For this processing - it is not really clear to me. I would appreciate opening a new issue to brainstorm on this.

**Comment by chombium** [comment]
@drasko sorry for not making myself clear enough :(

I was thinking about subscription with a wildcard to all topics for a device. If we have one or more devices which measure temperature and humidity and the topics are divided in two channels one for the temperature measurements and the other for the humidity measurements. The topics would be:
`channels/1/messages/my_dev/temperature` and `channels/2/messages/my_dev/humidity` respectively. If there is a client which wants to subscribe to all topics of `my_dev`, it will send a subscription request using wildcards with the following topic: `channel/+/messages/my_dev/#`. Let's say that the client has right to read the temperature, but not the humidity. I was wandering how will the subscribe process go, but after checking our mqtt code, I saw that everything is good there as we send proper replies for each topic subscription request and the client will get an acknowledgement for the temperature subscription and a denial message for the humidity subscription.

The implementation won't be hard indeed, but we should decide if we go with some feature switches, or we provide some mechanism for extending the basic functionality of Mainflux.
