### ISSUE TITLE
Grafana doesen't visualize data

### ISSUE THREAD

**Issue by nzeulin** [absmach/magistrala#445]
I'm trying to launch Mainflux, write some data to InfluxDB and then visualize it in Grafana.

I followed [this](https://medium.com/mainflux-iot-platform/mainflux-open-source-iot-platform-set-up-and-usage-70bed698791a) tutorial, and everything works fine until I need to get some graphs using queries.

Using `http://localhost:8086` as database source gives `502 Bad Gateway`, while default `http://mainflux-influxdb:80806` gives no errors. I tried to connect to database with `influx`, and it connects to `localhost:8086` by default. When I connect to `mainflux-influxdb:8086` and try to do something like `show databases`, I get `ERR: Post http://mainflux-influxdb:8086/query?chunked=true&db=&epoch=ns&q=show+databases: dial tcp: lookup mainflux-influxdb on 127.0.0.53:53: server misbehaving`

Sending messages to `localhost` with 'mosquitto_pub' is ok, but when I change host to `mainflux-influxdb`, I get `Unable to connect (Lookup error.).`

I guess it's some docker problem with resolving `mainflux-influxdb` name. I have already tried changing `mainflux-influxdb` to `localhost` in `mainflux/k8s/addons/influxdb/writer.yml` and `mainflux/docker/addons/influxdb-writer/docker-compose.yml`.

Also when I make query in Grafana using `mainflux-influxdb`, I can access all measurements and values (which I actually sent to `localhost`), but no point appears on a graph. What went wrong?

**Comment by chombium** [comment]
Hi @ga1nenergy,

If you are setting `http://localhost:8086` as a database source in the Grafana admin panel that would mean that the InfluxDB runs on the same host which is not the case. Grafana and InfluxDB run in separate containers and that's why you get the error and when you use `http://mainflux-influxdb:8086` you get no errors, because the `mainflux-influxdb` is the host of the InfluxDB container in which the database is runniung. That's why you are able to read the InfluxDB data from the Grafana container when specifying `mainflux-influxdb` as host.

From what you've written I suppose you are trying to connect to the InfluxDB and you are sending messages via mosquitto from your host machine (from localhost). The `mainflux-influxdb` host is known only to the docker environment and that's why you can not connect directly to it by it's hostname. We have configured port mapping for the InfluxDB's container port 8086 to localhost and the same is done for the MQTT client. That's why when you send messages via mosquitto from localhost they land in the database.

If you see access the InfluxDB from the Grafana container and you don't see any data in the dashboard graph, I think that there is some problem with the configuration of the query.

Could you please send a screenshot from the configuration of the query for the graph which you are showing in your dashboard?

Best Regards,
Jovan

**Comment by nzeulin** [comment]
Hi @chombium,

Thank you for your detailed explanation. The problem really was in query. In Grafana I should have replaced `field(value)` with `field(*)`. Initial query looked like 

`SELECT "value" FROM "autogen"."messages" WHERE ("Channel" = '1')`, 

and I needed 

`SELECT * FROM "autogen"."messages" WHERE ("Channel" = '1')`. 

Somehow I didn't pay attention previously to this `field(value)`

**Comment by chombium** [comment]
@ga1nenergy I'm glad it worked out. Have fun using Mainflux :)
