### ISSUE TITLE
Use message Time field as a time for InfluxDB points

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala#454]
In order to provide more meaningful measurements, consider using time value received from the message as the value of "time" column when saving data in InfluxDB.

**Comment by drasko** [comment]
Also, please use `channels` for Influx `tags`. This way we can obtain one Influx `serie`.

`measurement` + `tagset` = series as a whole
`measurement` + `tagset` + timestamp = single point

![image](https://user-images.githubusercontent.com/149944/48262979-cf240500-e424-11e8-8627-7723f06db5f6.png)

Making `tagset` = `channelID` we'll obtain one graph per channel. This makes sense, because we might represent one object of interest (autonomous vehicle for example) with different channels over which we send messages in parallel (speed, position, engine_temperature, ...). To obtain several series as a separate (and potentially overlapping) graphs we can do:
```
measurement = "autonomous_vehicule"
tag = <speed_channelID>
```
and so on.

**Comment by drasko** [comment]
@dusanb94 take a look at the old implementation: https://github.com/AtticFantastic/mainflux-influxdb-writer/blob/master/message.go#L42-L46

Also, go though this presentation: http://what-not-todo-influxdb.herokuapp.com

**Comment by dborovcanin** [comment]
As @drasko suggested, #455 is updated to use only `Channel` and `Publisher` as tag keys. All the other Message fields are represented as value keys. However, everything I wrote in my previous comment is still applicable to all Reader and Writer services.

**Comment by drasko** [comment]
https://github.com/mainflux/mainflux/pull/501 adds `name` to tagset as well in order to facilitate following scenario: one device (for example LoRa sensor) reads several measurement types (tamperature, humidity and pressure) and sends them to one channel. In that case e have same publisher and same channel and we need to add measurement name to form separate Influx serie and prevent messages overwriting (as they would have the same timestamp, same publisher and same channel).
