### ISSUE TITLE
Add Bootstrapping service

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala#513]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Bootstrap service will provide initial Thing configuration. Besides this initial configuration, bootstrap service provides simple access control over Things. It’s possible to add or remove Thing to/from the whitelist in order to enable or disable message exchange for it. Initial BS endpoint will be provided in the Thing during the manufacturing process. Provisioning a new Thing is as simple as sending correspoinding data to this service. Once Thing is active, it’s aware only of the existence of that BS endpoint, so it sends a request for initial config to BS service. Once the Thing is bootstrapped, it’s possible to add it to the whitelist, so that it can exchange messages using Mainflux. Bootstrapping does not implicitly whitelist the Thing, so it has to be done manually. Thing configuration includes a list of Channels the Thing is connected to, so whitelisting is basically connecting and disconnecting the Thing to/from them. These Channels need to be preprovisioned. 
3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is should-have feature.

**Comment by chombium** [comment]
Quick question: Should we call this service bootstraping service or onboarding service?

Regarding the security of this process we must also ensure the authenticity of the sent bootstraping (onboarding) request and the thing it self. We must be sure that each request comes from a known thing. Even though the requests will be approved by an administrator (the whole responsibility is pushed to the user) we must add some security mechanisms to strengthen the security of this service in order to avoid its misuse.

**Comment by dborovcanin** [comment]
@chombium I agree with you. In fact, I think that we can completely remove this `self-bootstrapping` section for two reasons: it brings really nothing and it breaks the basic idea of the service.
1) It does nothing useful because the flow will be pretty much the same and eventually will include administrator adding (updating, in this specific case) Thing on the service side, so no visible benefits here. Also, this introduces possible security issues.
2) It breaks service idea because the idea is simple: if you want a Thing to be able to bootstrap itself, you need to provision it on the Bootstrap service side.
The administrator can always check logs for the unknown Things that attempted to bootstrap and provision those on the bootstrap service side.

**Comment by dborovcanin** [comment]
@chombium I've removed `self-bootstrapping` section, it's a really bad idea.

**Comment by chombium** [comment]
@dusanb94 the self-bootstrapping is not bad it's actually a great idea, but it takes a big effort to do it right in terms of security, so that we can make sure that the thing is the thing it "pretends"/"shows" to be.

As a start we could eventually build something similar an account activation url when you register to some service. We would say that for each thing we'll have a separate activation url or token which will be "flashed" on the device in a secure environment and if something goes wrong with the thing (get's stolen or compromised) , the admin will deactivate the url/token.

The proper thing to do though would be to enable and build something like [Intel SDO](intel.com/securedeviceonboard) or some kind of hardware authentication on the thing it self something like Microchip's [ATECC508A](https://www.microchip.com/wwwproducts/en/ATECC508A) or [ATECC608A](https://www.microchip.com/wwwproducts/en/ATECC608A). The proper and secure implementation depends on the capabilities of the things themselves as well.

The self-bootstrapping an interesting thing to play with ;)

**Comment by dborovcanin** [comment]
@chombium Of course, self-bootstrapping would be a perfect solution, but I think that this should be discussed in a separate issue. It's much more complex than it initially looks like and the flow is really not much different than this usual bootstrapping flow.
