### ISSUE TITLE
Add pagination in API responses for Bootstrap service

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala#540]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Add pagination to all `list` endpoints of Bootstrap Service. Currently, a simple list of entities is returned instead of the actual page.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is a must-have feature.

**Comment by chombium** [comment]
Hi @dushanb94, as you requested, I will write my concerns about the `/bootstrap` endpoint naming here...
I completely agree with you that the bootstrap service which you currently work on is thing related, I'm just wandering what would happen in the future if we have some new bootstrapping service for another entity. Because of the fact that the `/bootstrap` enpoint would be taken, we would probably have to either add inconsistent api endpoint like `/bootstrap/<entity>` or brake the api add `/bootstrap/things`  and `/bootstrap/<entity>s` , so that we keep the api consistent.
On the other hand, on first sight, only by reading the enpoint path `/bootstrap` it's hard to understand what this enpoint is for.

We could also go with the "prefix scheme" and instead of adding one top level route we do the routing to the services like `/things/bootstrap` and so on ...

This is my personal view, but I can also live with the current implementation.
