### ISSUE TITLE
Introduce organizations (user groups) for full multi-tenancy

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#649]
Organizations (or groups of users) should be introduced to enable full multi-tenancy.

Admin account equally should be introduced:
- Admin of the organization
- Admin of the whole Mainflux system (admin of admins)

Related to https://github.com/mainflux/mainflux/issues/397

**Comment by mteodor** [comment]
We should investigate if it would be possible to use some 3rd party identity management (IAM) that would handle multi-tenancy and user rights and roles. Each user entity in the 3rd party IAM would be connected with one user in the mainflux core and IAM would keep that relation. When authenticated against 3rd party IAM request would be forwarded with information about mainflux user, probably in the header.
Some of the features, like admin access, might be controlled with api gateway which would rely on used IAM

**Comment by drasko** [comment]
@mteodor this is eaxctly how Hydra is working: https://www.ory.sh/docs/ecosystem/overview - a requests are inercepted by Oathkeeper proxy, which acts as a Policy Enforcement Point (PEP). Requests are then forwarded to Keto, which acts as a Policy Decision Point (PDP) (more on terminology [here](https://ccskguide.org/policy-decision-points-policy-enforcement-points/)).

[XACML](https://en.wikipedia.org/wiki/XACML) and [SAML](https://en.wikipedia.org/wiki/SAML_2.0) can be used for this purpose.

Keto is very interesting, as it uses [OPA](https://www.openpolicyagent.org/). Regarding from this issue: https://github.com/ory/keto/issues/47, they depricated [Ladon](https://github.com/ory/ladon) and moved on with OPA.

**Comment by drasko** [comment]
Interesting blog regarding OPA and policies: https://blog.verygoodsecurity.com/posts/building-a-fine-grained-permission-system-in-a-distributed-environment/

**Comment by drasko** [comment]
References for research and study:

https://blog.verygoodsecurity.com/posts/building-a-fine-grained-permission-system-in-a-distributed-environment/

https://www.openpolicyagent.org/

https://www.ory.sh/docs/ecosystem/overview

https://github.com/ory/keto/issues/3

https://ccskguide.org/policy-decision-points-policy-enforcement-points/

https://github.com/summerwind/opa-nginx-rbac

https://github.com/cloudflare/cfssl

https://en.wikipedia.org/wiki/XACML

https://en.wikipedia.org/wiki/SAML_2.0

https://en.wikipedia.org/wiki/Attribute-based_access_control

https://en.wikipedia.org/wiki/Role-based_access_control

https://www.youtube.com/watch?v=XEHeexPpgrA

**Comment by chombium** [comment]
Could we please first define what are the requirements and how will everything be organized before we choose the implementation method and tools?

At the moment all the things are owned by a user.
The way I see the restructuring to organizations:
* each organization can have sub-organizations or member users
* each organization have admin users which can add/remove users and sub-organizations
* each organization owns things (devices) which can be assigned to users
* each user can own a thing (device). This would be useful in case of BYOD (Bring Your Own Device) scenarios.
* access rights read/write to a thing (device) can be given per thing class. The things will be grouped  For i.e. a temperature analysis app would have read access to all temperature sensors in an area 
* access rights read/write can be added to a single thing instance
* for a multi-tenant system we could have one root org in the system and all tenants are sub-orgs. The question is what are we going to do if there should be data sharing between the sub-orgs (tenants)

Questions:
1. How are we going to manage the things? Will they be owned by an organization or a user?
2. How are we going to propagate the permissions? Will the child org inherit the permissions of the parent org and can overwrite them?
3. One can send multiple measurements for different properties in a single SenML message. At the moment the only way to specify thing properties is via the [metadata](https://github.com/mainflux/mainflux/blob/master/things/things.go#L20). Do we need create an extra ThingProperty entity, so that we can have fine grained access to a thing property? This can be useful if we have sensors which measure different physical properties and we want to control which property can be accessed by which app.
4. What would happen if we want to share data across organizations? A practical example would be when an organization buys many sensors and hires a maintenance company to monitor and repair the sensors. The maintenance company might need to read some status/monitoring data to check the state of the sensors.

@mainflux/contributors what are your thoughts on this?

**Comment by nmarcetic** [comment]
I fully agree with @chombium. We are missing requirements and concepts. 
I'm least concerned about the tech/tooling part.

We agreed to continue the discussion here.
I like your points @chombium but also concerns, right questions.

First, I would like to pick your brains on this [access control](https://github.com/mainflux/mainflux/issues/377) topic because I think it will move your minds in other directions. 

What if we can keep everything as is, the only user owns the device, there are no multiple user roles in the system (I don't think we need it), etc... and introduce [ABAC policies](https://en.wikipedia.org/wiki/Attribute-based_access_control). 

Let's stick with organizations/groups first. For the sake of simplicity, let's call it a group. 
IMHO Group is a new entity in Mainflux, which class any other objects with the same type (user, things, channels).  
Example Group structure: 
```
type Group struct {
  type: int // We can have predefined group types that we support with iota 
  objects: []string // UUID's of grouped objects with the same type (users, things ,channels)
  metadata: map[string]interface{} // For your custom stuff , name description etc... its user-defined.
}
```
As you can see, it's lean and simple with only one purpose, to group/class the objects of the same type (technically it would be complicated to group objects with different types, and I am pretty sure we should NOT mix it). 

Back to [ABAC policies](https://en.wikipedia.org/wiki/Attribute-based_access_control).

Any entity in Mainflux is an attribute (user, thing, channel, group), represented by its UUID. Following this logic, we can create a policy with read/write permissions to any attribute. The policy should answer to question:

Who can/cannot perform action X on attribute Y. 

Take a messaging, for example. We have a thing which can pub/sub to channel. Policy would define

`Thing can/cannot pub/sub on channel X`
Or 
`User can/cannot view/edit group X`
Or
`User can/cannot view/edit thing X`
Or
`User can/cannot view/edit user X`
Or 
`Group can/cannot view/edit attribute X` 

Etc...

The tricky part is when a subject (in policy terminology an entity that wants to perform an action) has multiple policies, like at the same time, its a member of N groups with different permissions. 
But this is more a question of tech/tools and impl.


As described in  [access control](https://github.com/mainflux/mainflux/issues/377) issue, I researched technology/tools, and currently, my favorite is [Casbin](https://casbin.org) library, doing some code spikes to verify the idea ^

I think such a generic approach where you have the flexibility to design your access control will cover most use cases. That policy logic can be placed in new AuthZ service which will expose both gRPC (internal use) and HTTP API (public use), but this is again a question for impl; let's leave it for #later.

One more thing to consider is, Do we need channels then? Do we need to connect things if we have groups and policy management? 

let me know your thoughts @mainflux/contributors

**Comment by anovakovic01** [comment]
I think that ABAC policies are the right way to go. Also, I agree that groups should be really simple as you suggested (have just ID and metadata).

> One more thing to consider is, Do we need channels then? Do we need to connect things if we have groups and policy management?

This will change a lot of things regarding MF. I think that we can develop a solution that doesn't need a chan ID. Instead of connecting to the channel, we can say in the policy: this group has access to this topic and all of its subtopics. And that's it. Then you can have a really generic solution with fine-grained access control. You'll be able to control even read/write access to the topics.

**Comment by nmarcetic** [comment]
@anovakovic01 Fully agree, let's remove everything we don't need in channels regarding access control (e.g connections) and keep just things that we need for messaging like topics, metadata, etc...

**Comment by drasko** [comment]
@nmarcetic - fully agree for the groups - lean and make sense.

I also prefer ABAC approach.

@anovakovic01 - channels are groups, a poor-man's communication or permission gorups.

>  Instead of connecting to the channel, we can say in the policy: this group has access to this topic and all of its subtopics.

True - insterting a thing into a group that has a permission to write to a certain channel is indeed same as connecting it to a channel.

With full-blown access control mechanism channels should become obsolete.

> I think that we can develop a solution that doesn't need a chan ID

We neet to think how we will represent a topic, as `channel` is an abstraction over MQTT topic, REST URL, CoAP URL and WS.

**Comment by chombium** [comment]
@drasko, @nmarcetic, @anovakovic01 I fully agree with all of you when we are talking about the data flows and who has access to which data.
What are we going to do about managing the thing and the CRUD operations on them? Are we still going to say that all of the things are owned by a single user or we'll change this and say that a group can also own things which is the common case in real world scenarios? If we go for the later we would also need some concepts for delegation of management rights and transfer of ownership. Ins such cases we would also need something like "thing history" in which it will be tracked what has happened with the thing over a period of time.

**Comment by drasko** [comment]
@chombium I think we should aim for later, because we are targeting enterprise context here.

@nmarcetic @anovakovic01 we'll need a spec that describes all of this in a form of MIP (Mainflux Improvement Proposal ;)).

**Comment by chombium** [comment]
@drasko, @nmarcetic, @anovakovic01 Tell me how can I help writing the MIP ;)

**Comment by drasko** [comment]
@chombium we plan opening a repo like [this](https://github.com/ethereum/EIPs).

@nmarcetic will add the input and then you can take it from there.

**Comment by nmarcetic** [comment]
@chombium Good question ^ 
`What are we going to do about managing the thing and the CRUD operations on them` I would leave as is, so the ONLY user can own and create a thing, but user can give read/write permissions to the group, so group A can read/write thing B (same as owner). Because being `owner` is nothing more than filed, a policy with read/write or `*` would give you the same "power", but we will keep simplicity.

**Comment by chombium** [comment]
@nmarcetic agreed. That's exactly what I had in mind as well. 

One other thing a bit off topic, but related: I think it would be also nice to also add a "service book" or "life history" for the things. Usually the sensors and the devices are assigned to someone to use and then they are returned or reused for other purpose. It would be nice if we have a log what has happened with a device from it's acquisition to it's decommissioned.  I guess such things can easily be implemented by the users based on our Event Sourcing. The question is if we need to add few more events so that we fire proper events. I know we have things like `thing.connect` and `thing.disconnect`, but I guess we'll have to adjust them too or even add two new events like "thing add/remove from group".

**Comment by jruizaranguren** [comment]
Hi, all. Is the MIP about multi-tenancy already in progress? I would like to contribute.

My 2 cents about the topic: I think that access control and multi-tenancy are related but it is not the same problem. Access control can help only partially with multi-tenancy requirements:

* data segregation constraint: each tenant should have an isolated data space (as in [NATS 2.0 Accounts](/https://docs.nats.io/whats_new_20#accounts) or [Vernemq mountpoints](https://docs.vernemq.com/configuration/listeners#mountpoints)). Every component where data is stored (no matter if transient or persistent) should control this. 
* Authentication: Access to tenant space requires proper credentials (JWT, for instance).
* Administration: Each tenant (administrators) will be able to manage own users, things, access control rules, dashboard options, etc.
* Scaling: Potentially each tenant could produce a different resources usage of the system, requiring rate limiting, quotas, exclusive deployment resources, etc.)
* Audit: Many systems will probably want some audit over system usage. Again this must be provided per tenant.
* Billing: Related to previous topics, billing may be affected by system resources usage.

Mainflux current architecture is in a good shape to provide multi-tenancy. The only component that I do not see how to extend is Redis Streams (other than dirty hacks such as event attributes or multi-database settings).

**Comment by drasko** [comment]
@anovakovic01 I think that MIP issue has to be officially opened.

**Comment by drasko** [comment]
For the reference, comparison Casbin vs OPA: https://github.com/ory/keto/issues/47#issuecomment-419764819

Also, I noticed that it can be done as a library: https://www.openpolicyagent.org/docs/latest/#5-try-opa-as-a-go-library

**Comment by drasko** [comment]
@mteodor how are we doing with this one? Can you please explain here what has been done in https://github.com/mainflux/mainflux/pull/1228 and what are the future plans.

**Comment by drasko** [comment]
@dusanb94 do not forget to close this one once group migration is done.

**Comment by dborovcanin** [comment]
This issue has been resolved a long time ago.
