### ISSUE TITLE
Assign Writer(s) to a channel

### ISSUE THREAD

**Issue by bbokun** [absmach/magistrala#708]
1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
When messages are sent to Mainflux, and more than one Writer is installed, all of the messages which pass the normalizer are stored via the Writers in all of the activated storage databases.
There should be the possibility to assign Writer(s) to a channel which should be used to write the data to the storage database(s)

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
I think this is a very important feature. 
Example: If I post geo-location data, I want to store the data only in MongoDB, but not in the InfluxDB. 

Again, thank You for the cool work!

Regards, 
Boris Bokun
strictit d.o.o.
Beograd

**Comment by drasko** [comment]
I think that this is an important feature, @bbokun thanks for suggesting this improvement.

**Comment by drasko** [comment]
@bbokun we can add an endpoints into each of writers so that you can dynamically tell them to which topics to subscribe, and from which to unsubscribe.

The only problem with this dynamic info is that writers become stateful, and they must share this state with other instances for scaling. That means that they must keep their channel map somewhere in Redis or etcd.

**Comment by chombium** [comment]
@drasko another idea that came across my mind is to take the hardcoded wirings (nats pub/sub topics) between the adapters, the normalizer and the writers outside the code and pass them as envvars. This way the user can set custom nats subscription topic for a writer and add a custom component which will subscribe to the normalizer's topics. This custom component can do message introspection and depending on some rule publish the message to a topic on which a particular writer is subscribed. This way we add flexible message routing and the scaling is simple as we'll scale instances of a particular writer with a specific configuration. The whole config will be self-contained in the deployment configuration.
What do you think abou this?

**Comment by bbokun** [comment]
I looked a little bit in the code, and think that I understand what the challenge is. 
If I read it the right way, please correct me if I am wrong - the normalizer is subscribed to all channels with the ">" wildcard. It tries to find out if the format is SenML, and in case it is, it publishes it on the "out.senml" topic. The writer on the other side is subscribed to the latter topic, and handles the saving into the registered writers. The main issue here is how to find out to which writer the data has to be routed to which writer. Some channel to writer mappings would probably be the solution. The custom component @chombium suggested - would also have to resolve the channel-writer mappings and so have the same need for synchronization as @drasko wrote.
Sorry if I understood something wrong.

**Comment by chombium** [comment]
@bbokun you've understand everything correctly. :)
I wouldn't go with dynamic message routing, because in that case you would have to many moving components in the system and to get the state of the system you'll have to keep in sync all of the routes. If you want to troubleshoot some problem the things become far more interesting. First you have to determine the state of the system at the time the problem happened and then trace your actual problem. Maybe some kind of central router which will keep the state will do the trick. The state of the system must also be persited, ideally in such a way that if you redeploy everything, the system can be brought into the state it was before.
IMHO the message routing shouldn't change dynamically at all. If someone always needs some different processing/storage for the same class, same format of messages then he/she should rethink the whole system setup.

That's why I suggested that the message routing is set at deployment time. You'll habe stable system architecture and you'll aways know how the system behaves and how are the messages processed. If you want to change something you will redeploy some components with different configuration, but the system does not change at runtime.

In my use case I have small battery operated sensors which don't have a rtc (real time clock). When I send the messages with the measurements I could call some ntp server to ask for the time, but that would drop my operation time in half, because I would have to do two requests. So what I have is a custom http adapter which adds a timestamp and repacks the messages as senml. If I could've rewire the http adapter I would've added another custom component (like middleware) which would do the needed extra processing.

I personally think that the message routing should/does not change that often, so that we need to get to solve some system state synchronization problems. If the message routing changes dynamically, than we have a non-deterministic system and it would be hard to keep the system running stable.

That's why I suggested configurable pub/sub topics. You can have a custom component which subscribes to `out.senml` and `out.unknown` and based on the message contents (the channel in your case) you can decide to publish the message to a topic on which a specific writer is subscribed.

HTH.

Best Regards,
Jovan

**Comment by drasko** [comment]
@chombium I agree with you, and in the beginning I thought that we can define the subscription channels just with a simple config file or something.

Problem that @srados saw is that he actually creates new devices and these new devices receive new channels... But as you mentioned, this should probably be solved on a design level, and I think with the use of subtopics.

For example SUB on `channels.*.my_subtopic` could solve this, if you publish on each newly created channel with this subtopic that you want to save in DB.
