### ISSUE TITLE
Consider message normalization design changes

### ISSUE THREAD

**Issue by nmarcetic** [absmach/magistrala#780]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

Currently, there is a Normalizer service which is responsible for message normalization senlML -> Mainflux message. This service is [subscribed to all channels](https://github.com/mainflux/mainflux/blob/master/normalizer/nats/pubsub.go#L22) on NATS, taking senML as input and publishing Mainflux message as output to `out.<content_type>`. The problem here is double load, we are sending same messages (there are not really same, we did serialization) twice and this has a big impact on broker load. 
Consider moving message normalization to some other place or just avoid double traffic.   
 
3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Must have.

**Comment by drasko** [comment]
We need to establish do we need Normalizer as a microservice at all.

It can be provided as a library that all consumers import:
- Writers will impoert it and provide several normalization methods (senml+json, senml+cbor or none), ad this will be configurable (per channel)
- Other consumers (currently none written by Mainflux) will also import it and use it before processing messages)

If one wants to benefit on existing writers, he has to:
- Send messages in (non-normalized) SenML format (as it is today)
- Write his own Normalizer microservice if needed that will process his custom data format and transform it into some formats that Writers can process (either un-normalized SenML+JSON or SenML+CBOR), then re-publish on some NATS topic and instruct Writers to go and subscribe over there

**Comment by chombium** [comment]
IMHO having the Normalizer as microservice or a lib won't change anything if it is used. Sure one can tune fine if he/she wants to use it, but the actual problem is that the high load on NATS due to message duplication or to many messages in general. I think we can fix the problem by adding some time-to-live, TTL(age) and acknowledging of the messages which come from the adapters and are for the Normalizer. The messages will be deleted if the are older than the defined TTL or deleted after the are acknowledged by the Normalizer.

The problem is that NATS itself does not have these parameters. The good thing is that the [NATS Streaming Server](https://github.com/nats-io/nats-streaming-server) has these things. It can have [Store Limits](https://github.com/nats-io/nats-streaming-server#store-limits) defined per channel, which means we can configure the age (the TTL) of the messages per channel and have all Mainflux's Adapter message be deleted automatically if they are to old. Of course before setting the age of the message, the user should check if the set value is high enough so that the Normalizer processes the message before they are deleted. [Deletion of acknowledged messages](https://github.com/nats-io/nats-streaming-server/issues/721) is bad. The other nice feature that we can use is [Rate limiting matching](https://github.com/nats-io/stan.go#rate-limitingmatching) so that we are sure that the slow message consumers can manage to process all of the messages.

The only drawback which I've noticed so far is that we can not use [wildcard subscriptions nor sed to wildcard subjects](https://github.com/nats-io/nats-streaming-server#wildcards).

I'm still reading about the NATS Streaming Server, but I think it's worth analyzing it as a viable option and maybe building a PoC to get a better feeling what would be the scope of work for an eventual migration to it.

**Comment by nmarcetic** [comment]
@chombium I agree with you, but the problem is not in message accumulation, as I understand from your thoughts, maybe I am wrong? The problem is, as you said `high load on NATS due to message duplication or too many messages in general` So Adapter publish msg to NATS then Normalized take it, decode and publish again on NATS, so the message is back to NATS again. This applies to each message. So message traffic is always multiplied by two.

**Comment by anovakovic01** [comment]
> I think we can fix the problem by adding some time-to-live, TTL(age) and acknowledging of the messages which come from the adapters and are for the Normalizer. The messages will be deleted if the are older than the defined TTL or deleted after the are acknowledged by the Normalizer.

@chombium NATS doesn't have message persistence, so there is no point in defining TTL. It's just a simple pub/sub.

**Comment by chombium** [comment]
@anovakovic01 that's why I suggested that we evaluate the [NATS Streaming server](https://github.com/nats-io/nats-streaming-server/blob/master/README.md) which has these things. 
Btw. the NATS streaming server is not the same thing as "the plain" NATS which we use at the moment. My bad, now I see that I didn't add the [Introducing NATS Streaming](https://nats.io/blog/introducing-nats-streaming/) blog post.

I hope this makes my suggestion a bit clearer

**Comment by drasko** [comment]
I would propose that we close this issue due inactivity... I would leave the design as is for now, I think in the future we'll have to see with this design... NATS does not have QoS and this might be a problem IMHO. Additionally - NATS team has MQTT [on the roadmap](https://github.com/nats-io/nats-server/issues/812#issuecomment-530168551), and this might be very interesting as internal brokering solution with QoS (not only as an input adapter).

**Comment by nmarcetic** [comment]
@drasko Lets keep this opened, its very important

**Comment by dborovcanin** [comment]
We decided to use Normalizer as a lib for the following reasons:

1. High load on NATS @chombium mentioned.
2. Simplifications in development and deployment due to Normalizer service removal.
3. Better control on the consumer-side (e.g. writers): Currently, the writers are receiving normalized messages and store one by one. With the Normalizer as a lib, we have options to use bulk write and transactions.
