### ISSUE TITLE
Create error reporting channel when creating a thing

### ISSUE THREAD

**Issue by anovakovic01** [absmach/magistrala#790]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Mainflux should automatically create an error reporting channel for every thing that is provisioned. When going through bootstrap procedure, a thing should receive error reporting channel ID from `bootstrap` service. We should also consider creating specific channels for status change, where a thing will report it's own status. 

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
These features will be nice to have.

**Comment by drasko** [comment]
This is not on platform to decide IMHO, it's woo opoinionated. User should be capable to add or not error channel if he wants to.

What we can do is document a set of best practices for debugging.

**Comment by nmarcetic** [comment]
` where a thing will report it's own status.` Digital Twin #730 Solves this.

**Comment by chombium** [comment]
Couldn't we simply add a NATS channel subject(s) like errors.thing.<thing_id> or even make the subject configurable, so that the users can create custom subjects and group errors from more devices on the same channel?

A document on debugging and troubleshooting in general would be a nice thing to have.

@nmarcetic @darkodraskovic do we have a concept how the things will report their state? IMO simply offering an API endpoint won't be good. I think it would be better if we provide pub-sub mechanism, so that interested parties are informed when something happens and they don't have to pool the state of the things.

**Comment by nmarcetic** [comment]
@chombium Exactly! But not over NATS, over MQTT because we don't know who are consumers, Interested parties (maybe some UI app maybe third party system, who knows). Digital Twins will bring something similar to [this](https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-mqtt.html)

**Comment by drasko** [comment]
@anovakovic01 if you are OK with this, we should close this issue.
