### ISSUE TITLE
Webpack failed to compile - Mainflux

### ISSUE THREAD

**Issue by 2014siavash** [absmach/magistrala#80]
Hi,
My problem is about mainflux-ui. More precisely, i cannt run the UI due to the following error:
Can some one help me how can i fix this?

siavash@ubuntu:~/Desktop/Mainflux/mainflux-ui$ sudo ng serve
[sudo] password for siavash: 
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Date: 2017-08-15T09:59:04.143Z                                                           
Hash: 67952886eeacdc6b6f7f
Time: 86139ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 53 kB {vendor} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 87.8 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.11 MB [initial] [rendered]

ERROR in /home/siavash/Desktop/Mainflux/mainflux-ui/node_modules/@angular/cdk/typings/rxjs/rx-operators.d.ts (11,10): Module '"/home/siavash/Desktop/Mainflux/mainflux-ui/node_modules/rxjs/Scheduler"' has no exported member 'IScheduler'.

webpack: Failed to compile.

**Comment by nmarcetic** [comment]
@2014siavash The bug is caused by [@angular/cdk requires rxjs >= v5.0.3](https://github.com/angular/material2/issues/5564)
The [pull request with fix](https://github.com/mainflux/mainflux-ui/pull/4) is submitted, pls w8 while some one from team merge this.

Thank you for reporting this one! :beer: 
Please use [official mainflux-ui repository](https://github.com/mainflux/mainflux-ui) for issues  , do not submit issues related with mainflux-ui here :)

Cheers
