### ISSUE TITLE
Add support for typed channels

### ISSUE THREAD

**Issue by anovakovic01** [absmach/magistrala#802]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
When a user is creating a channel, he should specify that channel's content type. If one wants to use some of the writers in order to persist data from these channels, one should provide DB schema as part of channel metadata. This DB schema will be sent over Redis Streams, so that writers can receive it and apply it to DB. After DB schema has been applied to DB, messages that come over this channel can be stored in an appropriate table created using that channel's schema.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
In order for writers to have any value when working with custom types, this is a must-have.

**Comment by drasko** [comment]
As menitioned in https://github.com/mainflux/mainflux/issues/800, we'll avoid attaching type to a channel. DB schemas will also be out of the scope of Mainflux middleware. We'll provide default Writers/Reades for SenML (JSON and CBOR), for all other semantics custom writes will be made (this is the easiest approach, otherwise trying to make something generic to satisfy all use-cases would result in unusable and complicated code).
