### ISSUE TITLE
Save things and users in the MongoDB

### ISSUE THREAD

**Issue by netoax** [absmach/magistrala#872]
**FEATURE REQUEST**

Since the `things` and `users` microservices can be plugged in a different software stack, I think it would be nice to support saving its entities in a non-relational database too. In my case, for example, I want to run both services on a constrained device that already uses the MongoDB. I'm not concerned about saving the entities in columns and rows with well-defined relationships. I think other developers could face the same (or similar) use case in the future.

What do you think about this request? I'd appreciate working to add this support.

**Comment by drasko** [comment]
I am not favorable to this PR. You can maintain an implementation in your GitHub for now, but I do not want something that is really no necessary to enter in the mainline codebase, so that maintainers need to take care about it.

MongoDB on constrained devices makes less sense IMHO then having PostgreSQL or SQLite. MongoDB has non-friendly AGPL license to be run on a gateway, and additionally support for 32-bit devices was discontinued.

PostgreSQL is well supported on 32-bit machines - both Intel, ARM or MIPS.
SQLite is probably even better candidate.

In general - for User and Thing entities we need strong consistance in distributed environment, and SQL databases are better fit there.

On the other hand, what could be interesting is a reseach of using CouchDB or even better [BarrelDB](https://barrel-db.org/) to leverage on their decentralized synchronization features and explore Cloud-Edge contol-plane data exchange via this synchronization protocol.

**Comment by drasko** [comment]
Closing due inactivity.
