### ISSUE TITLE
Add bulk connect

### ISSUE THREAD

**Issue by nmarcetic** [absmach/magistrala#898]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
As described [here](https://github.com/mainflux/mainflux/issues/484#issuecomment-544544684)
  Now when we have bulk creation of things and channels, thanks to #889  it would be nice to have an API that can connect things to channels in bulk.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Nice to have

**Comment by nwneisen** [comment]
I'm going to start taking a look at this.  I think it will go quickly after doing the bulk create for things and channels.  I'd like to do this is multiple small PRs.  I think it will make for an easier and faster review process for everyone.

**Comment by drasko** [comment]
@nwneisen fantastic. It is scheduled for next release, so it would be great if you could take it.

**Comment by nmarcetic** [comment]
@nwneisen Totally agree we should keep smaller PRs in order to make reviews faster.

**Comment by nwneisen** [comment]
I'm working on the endpoint for this and I'd like to get some opinions of what that should look like.  
@nmarcetic @drasko @manuio 

The current endpoint for a single connection is a PUT at `/channels/:chanId/things/:thingId`.  My initial thought was to create a POST at `/channels/:chanId` since a list of things will be included in the payload.  My issues with this are that I can include the `:chanId` in the payload, this path is already used for GET, and it isn't clear what this is doing.

I'm more in favor using a POST to `/connect` which includes the channel ID and a list of thing IDs in the payload.  `/disconnect` could be used later if bulk disconnect is also desired.

**Comment by manuio** [comment]
@nwneisen I would use POST `/channels/:id/things` with a payload of Things ID. This endpoint is already used to list Things connected to a Channel.

`/connect` could be used to connect multiple channels to multiple things.

**Comment by nwneisen** [comment]
@manuio I've thought about whether this change should be for connecting multiple channels to multiple things.  Having that endpoint would eliminate the need for multiple things for one channel.  It would follow the same reasoning for eliminating the single endpoints.

- Simplify the API by having only one way of doing something
- If the users only have one channel, then they only send one channel
