### ISSUE TITLE
Consider replacing Bone mux with Chi

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#963]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Currently Mainflux HTTP and WS use [Bone mux](https://github.com/go-zoo/bone).

New mux [Chi](https://github.com/go-chi/chi) that appeared in the meanwhile gives more modern impression and should be evaluated as a Bone replacement.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
nice-to-have

**Comment by nmarcetic** [comment]
Chi looks really interesting, light ( stdlib only), and performant. Yet I would mark this as a low priority, cause it does not bring real benefits (its control plane API, not performance-critical, bone served us quite well, except now with #1357 which will be fixed with #1358 and the issue will be opened (@mteodo you should probably [raise the issue](https://github.com/go-zoo/bone/issues) ).

**Comment by felixgateru** [comment]
This was addressed by this pr: https://github.com/absmach/magistrala-old/pull/47
